### ISSUE TITLE
New packages proposition

### ISSUE THREAD

**Issue by alexandrebrilhante** [JuliaQuant/Roadmap#13]
As discussed with @iblis17, it would be quite useful to develop two new libraries: `FinancialDerivatives.jl` to model and price derivatives and  `StochasticSimulation.jl` as a simulation engine to price instruments and backtest strategies which seems like missing piece of the puzzle. For the second package, a former professor of mine who has done extensive research on stochastic simulation methods and developed a similar library in Java ([SSJ](https://github.com/umontreal-simul/ssj)) would be willing to assist in the design. Below is a flowchart with existing packages we can use, extend or refer to.

I'm willing to carry both projects forward.

![slide1](https://user-images.githubusercontent.com/6617333/43932262-054acdf0-9c11-11e8-877a-b71258c0b009.jpeg)

**Comment by iblislin** [comment]
cc @femtotrader

**Comment by femtotrader** [comment]
You should have a look at
https://www.youtube.com/watch?v=dy7tXk403bM
it's about
- SDEModels.jl https://github.com/Godisemo/SDEModels.jl
- OptionPrice.jl (Fourier option pricing)

You should notice that there is also https://github.com/rcalxrc08/FinancialToolbox.jl for pricing

About backtesting, there is currently in Julia
https://github.com/dysonance/Strategems.jl
https://github.com/JuliaQuant/TradingLogic.jl

**Comment by alexandrebrilhante** [comment]
@femtotrader: the pricing packages you mentioned seem to be focused on options using Black-Scholes. My proposition would include other derivatives (swaps, futures) and methods to price them. As for the proposed `StochasticSimulation.jl` package, it could supplement `Strategems.jl`and `TradingLogic.jl` really well.

**Comment by femtotrader** [comment]
I will very pleased to give your StochasticSimulation.jl package some highlight by hosting it in https://github.com/JuliaQuant/ Github org.
Maybe you should first create it in https://github.com/brilhana where we could help
and move it to JuliaQuant when it will have enough features.
What is your opinion about it?

**Comment by alexandrebrilhante** [comment]
Sounds good. I wanted to submit a blueprint and get other contributors' feedback before starting the development. Will start now.

**Comment by femtotrader** [comment]
This JuliaCon 2018 lightning talk from https://github.com/bkamins may be worth looking https://juliacon2018.sched.com/event/FQ4D/performance-of-monte-carlo-pricing-of-asian-options-using-multi-threading?iframe=yes&w=100%&sidebar=no&bg=no#

https://www.youtube.com/watch?v=Ni9A9B3zoXA

**Comment by femtotrader** [comment]
FinancialDerivatives.jl is now available at:
- https://juliaquant.github.io/FinancialDerivatives.jl/dev/ (documentation)
- https://github.com/JuliaQuant/FinancialDerivatives.jl (code)

**Comment by iblislin** [comment]
:tada: :tada: :tada:
