### ISSUE TITLE
Decide whether to implement FinancialTimeSeries as a type

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/Roadmap#2]
I'm really not in favor of this because of all the duplication of code that happens from TimeSeries.

My current thinking is to add a parameterized metdata field to the TimeArray type and occupy that space with an `Instrument` type.

**Comment by multidis** [comment]
This would reduce nearly-duplicated code. Can we setup some performance tests with a large `TimeArray`, comparing the following options:
1. Bare `TimeArray`
2. TimeArray metadata-branch, parameterized type
3. TimeArray with arbitrary metadata slot
4. My current FinancialTimeSeries [type](https://github.com/multidis/FinancialSeries.jl/blob/master/src/financialtimeseries.jl#L5)

**Context A:** Repeated backtesting. For the test, let's say we use EMA calculation on a large array and go over cases 1:4 above.

**Context B:** Real-time order logic, possibly with lazy lists. For the test, check timing and memory allocation when assembling a large array by appending one "row" at a time.

**Comment by milktrader** [comment]
I can push the TimeSeries branches and you can push your FinancialTimeSeries implementation as a branch for now. How does that sound? We can open an issue for FinancialTimeSeries (create a branch with new type) and assign that to you @multidis. I've already assigned myself the TimeSeries branches here. 

https://github.com/JuliaStats/TimeSeries.jl/issues/159

**Comment by milktrader** [comment]
@multidis you should have push/pull access to FinancialSeries and FinancialBlotter now. While you're still inspecting the latest state of the code, perhaps you can push branches for now until we decide on a cohesive plan for the master branch.

**Comment by multidis** [comment]
Let's try that @milktrader . To work with branches from Julia: `Pkg.clone("branch-url")` would re-write `origin` for the package, is there a convenient way to switch between branches locally?

**Comment by milktrader** [comment]
`$ git checkout master`
`$ git checkout my_brilliant_refactor`

Do this in the `.julia/v0.4/FinancialSeries` directory, e.g.

To create the original branch

`$ git checkout -b my_brilliant_refactor`

**Comment by multidis** [comment]
Performance tests with [base](https://github.com/multidis/QuantProfiling.jl/blob/master/src/timearray_type_base.jl) and parametric [metadata-augmented](https://github.com/multidis/QuantProfiling.jl/blob/master/src/timearray_type_fintswrap.jl) `TimeArray` suggest that at least in the case of `FinancialSeries.Instrument` meta-value the performance is nearly unaffected. Thus, it seems to make sense to proceed by introducing a meta-field in `TimeSeries.TimeArray`.

**Comment by milktrader** [comment]
Nice work. Thanks! This does push forward the idea to include a parameterized metadata field in TimeArray.

**Comment by milktrader** [comment]
Closing this since TimeArray has meta field now.
